"""
Two
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

Fibn = [1, 2]  #declaring the list

first = 1
second = 2
x = 0
x = first + second   # add the two previous numbers together
while x <= 4000000:  # Fib number up to 4 million
    Fibn.append(x)   # add Fib number to the list
    first = second
    second = x 
    x = first + second
print(Fibn)
evens = []
for x in range(len(Fibn)):  # checking only even numbers
    if Fibn[x] % 2 == 0:
        evens.append(Fibn[x])
print(evens)
total = 0
for x in range(len(evens)):
    total += evens[x]
print(total)
